name: Deploy to Apigee

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: execute commands
        run: |
          gcloud projects list
