name: Deploy to Apigee

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger from GitHub UI
    inputs:
      proxy_name:
        description: 'Proxy Name'
        required: true
        type: string
      target_url:
        description: 'Target API URL'
        required: true
        type: string
      port_context:
        required: true
        type: string

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log starting of Api Proxy ApiGee Infra creation 
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_Id }}
          logMessage: |
              About to create api proxy creation ${{ github.event.inputs.proxy_name }} .. ⛴️


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
        env:
          HOME: $HOME

      - name: Replace Target URL in XML
        run: |
          sed -i 's#\${target.url}#${{ github.event.inputs.target_url }}#g' apiproxy/targets/default.xml

      - name: execute commands
        run: |
          gcloud projects list
          ls && pwd
          zip -r proxy.zip apiproxy
          apigee_revision=$(curl --fail -X POST \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F "file=@proxy.zip" \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/apis?action=import&name=${{ github.event.inputs.proxy_name }}" \
          --silent | jq --raw-output .revision)
          echo "::set-output name=apigee-revision::$apigee_revision"
          echo "apigee_revision=$apigee_revision" >> $GITHUB_ENV
          echo "proxy_name=${{ github.event.inputs.proxy_name }}" >> $GITHUB_ENV

      - name: Deploy API Proxy to Apigee
        run: |
          curl --fail -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/environments/eval/apis/${{ env.proxy_name }}/revisions/${{ env.apigee_revision }}/deployments?override=true"

      - name: Create API Product
        run: |
          curl --fail -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d '{
                "name": "My-API-Product",
                "displayName": "My API Product",
                "approvalType": "manual",
                "attributes": [],
                "description": "API Product for My API",
                "apiResources": ["/"],
                "environments": ["eval"],
                "proxies": ["${{ env.proxy_name }}"],
                "quota": "10000",
                "quotaInterval": "1",
                "quotaTimeUnit": "minute"
              }' \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/apiproducts"

      - name: Create Developer
        run: |
          curl --fail -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d '{
                "email": "lucarocco934mag@gmail.com",
                "firstName": "luca",
                "lastName": "rocco",
                "userName": "LucaR"
              }' \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/developers"

      - name: Create App and Associate with Developer
        run: |
          curl --fail -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d '{
                "name": "MyApp",
                "apiProducts": ["My-API-Product"],
                "keyExpiresIn": "100000000",
                "attributes": [],
                "scopes": []
              }' \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/developers/lucarocco934mag@gmail.com/apps"
        
      
      - name: UPSERT API Proxy Entity to Port
        uses: port-labs/port-github-action@v1
        with:
          identifier: "${{ env.proxy_name }}"
          title: "${{ env.proxy_name }}"
          blueprint: ${{ fromJson(inputs.port_context).blueprint }}
          properties: |-
            {
              "proxy_name": "${{ env.proxy_name }}",
              "revision": "${{ env.apigee_revision }}",
              "status": "deployed",
              "environment": "eval"
            }
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          runId: ${{ fromJson(inputs.port_context).run_Id }}

     
