name: Deploy to Apigee

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger from GitHub UI
    inputs:
      proxy_name:
        description: 'Proxy Name'
        required: true
        type: string

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log starting of Api Proxy ApiGee Infra creation 
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_Id }}
          logMessage: |
              About to create api proxy creation ${{ github.event.inputs.proxy_name }} .. ⛴️


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
        env:
          HOME: $HOME

      - name: execute commands
        run: |
          gcloud projects list
          ls && pwd
          zip -r proxy.zip apiproxy
          apigee_revision=$(curl --fail -X POST \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F "file=@proxy.zip" \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/apis?action=import&name=${{ github.event.inputs.proxy_name }}" \
          --silent | jq --raw-output .revision)
          echo "::set-output name=apigee-revision::$apigee_revision"

     
