name: Deploy to Apigee

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: execute commands
        run: |
          gcloud projects list

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: $HOME/gcloud-key.json
          export_default_credentials: true

      - name: Authenticate to GCP
        run: gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
        env:
          HOME: $HOME

      - name: Clean up
        run: |
          rm $HOME/gcloud-key.json $HOME/gcloud-key-formatted.json

      - name: Create API Bundle
        run: zip -r proxy.zip apiproxy  # Adjust path if needed

      - name: Upload API Proxy Bundle to Apigee
        id: upload
        run: |
          apigee_revision=$(curl --fail -X POST \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F "file=@proxy.zip" \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/apis?action=import&name=my-api-proxy" \
          --silent | jq --raw-output .revision)
          echo "::set-output name=apigee-revision::$apigee_revision"

      - name: Deploy API Proxy to Apigee
        run: |
          curl --fail -X POST \
