name: Custom Workstation Image Build

on:
  push:
    paths:
      - './custom_workstation_image/*'
      - '.github/workflows/custom-workstation-image.yml'
    branches: [ "main" ]

permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/753105118496/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'github@serverless-container-images.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud auth configure-docker --quiet'
    - name: Build the Docker image
      working-directory: custom_workstation_image
      run: docker build . --tag gcr.io/serverless-container-images/workstation:$GITHUB_SHA --tag gcr.io/serverless-container-images/workstation:latest
    - name: Push the Docker image
      run: docker push -a gcr.io/serverless-container-images/workstation
      